esphome:
  name: discolight

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pw

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Discolight Fallback Hotspot"
    password: !secret hotspot_pw

captive_portal:

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO00
    num_leds: 76
    rgb_order: BRG
    name: "Disco Light Strip 0"
    effects:
      - pulse:
          transition_length: 0.5s
          update_interval: 0.5s
      - random:
          transition_length: 5s
          update_interval: 7s
      - strobe:
          colors:
            - state: true
              brightness: 100%
              red: 100%
              green: 90%
              blue: 0%
              duration: 500ms
            - state: false
              duration: 250ms
            - state: true
              brightness: 100%
              red: 0%
              green: 100%
              blue: 0%
              duration: 500ms
      - flicker:
          alpha: 95%
          intensity: 1.5%
      - addressable_rainbow:
          speed: 10
          width: 50
      - addressable_color_wipe:
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 1
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 1
          add_led_interval: 100ms
          reverse: false
      - addressable_scan:
          move_interval: 100ms
          scan_width: 1
      - addressable_twinkle:
          twinkle_probability: 5%
          progress_interval: 4ms
      - addressable_random_twinkle:
          twinkle_probability: 5%
          progress_interval: 32ms
      - addressable_fireworks:
          update_interval: 32ms
          spark_probability: 10%
          use_random_color: false
          fade_out_rate: 120
      - addressable_flicker:
          update_interval: 16ms
          intensity: 5%
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO04
    num_leds: 76
    rgb_order: BRG
    name: "Disco Light Strip 1"
    effects:
      - pulse:
          transition_length: 0.5s
          update_interval: 0.5s
      - random:
          transition_length: 5s
          update_interval: 7s
      - strobe:
          colors:
            - state: true
              brightness: 100%
              red: 100%
              green: 90%
              blue: 0%
              duration: 500ms
            - state: false
              duration: 250ms
            - state: true
              brightness: 100%
              red: 0%
              green: 100%
              blue: 0%
              duration: 500ms
      - flicker:
          alpha: 95%
          intensity: 1.5%
      - addressable_rainbow:
          speed: 10
          width: 50
      - addressable_color_wipe:
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 1
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 1
          add_led_interval: 100ms
          reverse: false
      - addressable_scan:
          move_interval: 100ms
          scan_width: 1
      - addressable_twinkle:
          twinkle_probability: 5%
          progress_interval: 4ms
      - addressable_random_twinkle:
          twinkle_probability: 5%
          progress_interval: 32ms
      - addressable_fireworks:
          update_interval: 32ms
          spark_probability: 10%
          use_random_color: false
          fade_out_rate: 120
      - addressable_flicker:
          update_interval: 16ms
          intensity: 5%
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO05
    num_leds: 76
    rgb_order: BRG
    name: "Disco Light Strip 2"
    effects:
      - pulse:
          transition_length: 0.5s
          update_interval: 0.5s
      - random:
          transition_length: 5s
          update_interval: 7s
      - strobe:
          colors:
            - state: true
              brightness: 100%
              red: 100%
              green: 90%
              blue: 0%
              duration: 500ms
            - state: false
              duration: 250ms
            - state: true
              brightness: 100%
              red: 0%
              green: 100%
              blue: 0%
              duration: 500ms
      - flicker:
          alpha: 95%
          intensity: 1.5%
      - addressable_rainbow:
          speed: 10
          width: 50
      - addressable_color_wipe:
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 1
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 1
          add_led_interval: 100ms
          reverse: false
      - addressable_scan:
          move_interval: 100ms
          scan_width: 1
      - addressable_twinkle:
          twinkle_probability: 5%
          progress_interval: 4ms
      - addressable_random_twinkle:
          twinkle_probability: 5%
          progress_interval: 32ms
      - addressable_fireworks:
          update_interval: 32ms
          spark_probability: 10%
          use_random_color: false
          fade_out_rate: 120
      - addressable_flicker:
          update_interval: 16ms
          intensity: 5%
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO12
    num_leds: 76
    rgb_order: BRG
    name: "Disco Light Strip 3"
    effects:
      - pulse:
          transition_length: 0.5s
          update_interval: 0.5s
      - random:
          transition_length: 5s
          update_interval: 7s
      - strobe:
          colors:
            - state: true
              brightness: 100%
              red: 100%
              green: 90%
              blue: 0%
              duration: 500ms
            - state: false
              duration: 250ms
            - state: true
              brightness: 100%
              red: 0%
              green: 100%
              blue: 0%
              duration: 500ms
      - flicker:
          alpha: 95%
          intensity: 1.5%
      - addressable_rainbow:
          speed: 10
          width: 50
      - addressable_color_wipe:
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 1
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 1
          add_led_interval: 100ms
          reverse: false
      - addressable_scan:
          move_interval: 100ms
          scan_width: 1
      - addressable_twinkle:
          twinkle_probability: 5%
          progress_interval: 4ms
      - addressable_random_twinkle:
          twinkle_probability: 5%
          progress_interval: 32ms
      - addressable_fireworks:
          update_interval: 32ms
          spark_probability: 10%
          use_random_color: false
          fade_out_rate: 120
      - addressable_flicker:
          update_interval: 16ms
          intensity: 5%
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO14
    num_leds: 76
    rgb_order: BRG
    name: "Disco Light Strip 4"
    effects:
      - pulse:
          transition_length: 0.5s
          update_interval: 0.5s
      - random:
          transition_length: 5s
          update_interval: 7s
      - strobe:
          colors:
            - state: true
              brightness: 100%
              red: 100%
              green: 90%
              blue: 0%
              duration: 500ms
            - state: false
              duration: 250ms
            - state: true
              brightness: 100%
              red: 0%
              green: 100%
              blue: 0%
              duration: 500ms
      - flicker:
          alpha: 95%
          intensity: 1.5%
      - addressable_rainbow:
          speed: 10
          width: 50
      - addressable_color_wipe:
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 1
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 1
          add_led_interval: 100ms
          reverse: false
      - addressable_scan:
          move_interval: 100ms
          scan_width: 1
      - addressable_twinkle:
          twinkle_probability: 5%
          progress_interval: 4ms
      - addressable_random_twinkle:
          twinkle_probability: 5%
          progress_interval: 32ms
      - addressable_fireworks:
          update_interval: 32ms
          spark_probability: 10%
          use_random_color: false
          fade_out_rate: 120
      - addressable_flicker:
          update_interval: 16ms
          intensity: 5%
